services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAINS: 'https://docker-eng-test.onrender.com'
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
      
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eng_test
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DOMAINS: 'https://docker-eng-test.onrender.com'
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
      
  mysql:
    image: mysql:8.0
    container_name: mysql_testing
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eng_test
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysqldata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      
volumes:
    mysqldata: