services:
  nginx:
    image: nginx:1.25.0
    container_name: nginx;
    build: .docker/nginx
    environment:
      DOMAINS: 'docker-eng-test.onrender.com'
      config.host: "docker-eng-test.onrender.com"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - nginx-proxy
      - default
    depends_on:
      - app
    expose:
      - 80
    ports:
      - 80:80
      
  app:
    container_name: app
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    environment:
      LANG: 'ja_JA.UTF-8'
      TZ: 'Asia/Tpkyo'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DOMAINS: 'docker-eng-test.onrender.com'
    volumes:
      - ./src:/var/www/html
    expose:
      - 9000
    port:
      - 9000:9000
      
  mysql:
    image: mysql:8.1
    container_name: mysql_testing
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eng_test
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysqldata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
      
volumes:
    mysqldata: